# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='job',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(default='location default', max_length=150),
        ),
    ]
